# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_num', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FightStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=140)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.CommonOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='JuryPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_mark', models.IntegerField()),
                ('opponent_mark', models.IntegerField()),
                ('reviewer_mark', models.IntegerField(blank=True, null=True)),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Jury')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=140)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.CommonOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=140)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('is_capitan', models.BooleanField()),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.CommonOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.TeamOrigin'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='scifight.Participant'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='points',
            field=models.ManyToManyField(to='scifight.JuryPoints'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Problem'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='refusals',
            field=models.ManyToManyField(related_name='refusals', to='scifight.Problem'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='scifight.Participant'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='scifight.Participant'),
        ),
        migrations.AddField(
            model_name='fight',
            name='juries',
            field=models.ManyToManyField(to='scifight.Jury'),
        ),
        migrations.AddField(
            model_name='fight',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Room'),
        ),
        migrations.AddField(
            model_name='fight',
            name='stages',
            field=models.ManyToManyField(to='scifight.FightStage'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team4', to='scifight.Team'),
        ),
    ]
