# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_num', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Completed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FightStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_num', models.IntegerField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Fight')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=140)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.CommonOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='JuryPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_mark', models.IntegerField(blank=True, null=True)),
                ('opponent_mark', models.IntegerField(blank=True, null=True)),
                ('reviewer_mark', models.IntegerField(blank=True, null=True)),
                ('fight_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.FightStage')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Jury')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=140)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.CommonOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderToJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Jury')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Leader')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=140)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('is_capitan', models.BooleanField()),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.CommonOrigin')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.FightStage')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Team origin',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('short_name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_date', models.DateField(default=django.utils.timezone.now)),
                ('closing_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.TeamOrigin'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='room',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='refusal',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='leadertojury',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='leader',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='leader',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='jurypoints',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='jury',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='scifight.Participant'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Problem'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='scifight.Participant'),
        ),
        migrations.AddField(
            model_name='fightstage',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='scifight.Participant'),
        ),
        migrations.AddField(
            model_name='fight',
            name='juries',
            field=models.ManyToManyField(blank=True, to='scifight.Jury'),
        ),
        migrations.AddField(
            model_name='fight',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Room'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='team4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team4', to='scifight.Team'),
        ),
        migrations.AddField(
            model_name='fight',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('tournament', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='refusal',
            unique_together=set([('fight_stage', 'problem')]),
        ),
        migrations.AlterUniqueTogether(
            name='leadertojury',
            unique_together=set([('leader', 'jury')]),
        ),
        migrations.AlterUniqueTogether(
            name='jurypoints',
            unique_together=set([('fight_stage', 'jury')]),
        ),
        migrations.AlterUniqueTogether(
            name='fightstage',
            unique_together=set([('fight', 'action_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='fight',
            unique_together=set([('room', 'fight_num')]),
        ),
    ]
