# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scifight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scifight_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
