# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='team3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='scifight.Team'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team4', to='scifight.Team'),
        ),
    ]
