# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0002_fight_alter_team3_team4_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scifight.Team'),
        ),
    ]
