# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0003_fix_jury_spelling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='is_capitan',
            new_name='is_captain',
        ),
    ]
