# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0004_fix_captain_spelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leadertojuror',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='leadertojuror',
            name='juror',
        ),
        migrations.RemoveField(
            model_name='leadertojuror',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='leadertojuror',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='juror',
            name='full_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='leader',
            name='full_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=140),
        ),
        migrations.DeleteModel(
            name='LeaderToJuror',
        ),
        migrations.AddField(
            model_name='juror',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scifight.PersonIdentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scifight.PersonIdentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scifight.PersonIdentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='identity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scifight.TeamIdentity'),
            preserve_default=False,
        ),
    ]
