# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0005_leader_alter_team_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='fight',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='fightstage',
            name='points',
        ),
        migrations.RemoveField(
            model_name='fightstage',
            name='refusals',
        ),
        migrations.AddField(
            model_name='fightstage',
            name='fight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scifight.Fight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurypoints',
            name='fight_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scifight.FightStage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refusal',
            name='fight_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.FightStage'),
        ),
        migrations.AddField(
            model_name='refusal',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Problem'),
        ),
    ]
