# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0005_add_identity_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_num', models.SmallIntegerField()),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Tournament')),
            ],
            options={
                'ordering': ['ordinal_num'],
            },
        ),
        migrations.AlterField(
            model_name='juror',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='scifight.PersonIdentity'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='scifight.PersonIdentity'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='scifight.PersonIdentity'),
        ),
        migrations.AlterField(
            model_name='team',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='scifight.TeamIdentity'),
        ),
        migrations.AlterUniqueTogether(
            name='fight',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fight',
            name='fight_num',
        ),
        migrations.AddField(
            model_name='fight',
            name='round',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='scifight.TournamentRound'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fight',
            unique_together=set([('room', 'round')]),
        ),
    ]
