# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0006_add_tournament_round'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fight',
            options={'ordering': ['round', 'room']},
        ),
        migrations.RenameField(
            model_name='commonorigin',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='teamorigin',
            old_name='name',
            new_name='place_name',
        ),
    ]
