# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0007_rename_some_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonOrigin',
            new_name='PersonOrigin',
        ),
    ]
