# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0008_add_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderToJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Jury')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scifight.Leader')),
            ],
        ),
        migrations.AlterField(
            model_name='fight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Not started'), (1, b'In progress'), (2, b'Completed')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='leadertojury',
            unique_together=set([('leader', 'jury')]),
        ),
    ]
