# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0008_rename_common_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamorigin',
            options={'verbose_name': 'Team origin', 'verbose_name_plural': 'Team origins'},
        ),
        migrations.AlterField(
            model_name='fight',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Team'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Team'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Team'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Team'),
        ),
        migrations.AlterField(
            model_name='fightstage',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Participant'),
        ),
        migrations.AlterField(
            model_name='fightstage',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Participant'),
        ),
        migrations.AlterField(
            model_name='fightstage',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scifight.Participant'),
        ),
        migrations.AlterField(
            model_name='juror',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='scifight.PersonIdentity'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='scifight.PersonIdentity'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='scifight.PersonIdentity'),
        ),
        migrations.AlterField(
            model_name='team',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='scifight.TeamIdentity'),
        ),
    ]
