# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scifight', '0009_add_LeaderToJury_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurypoints',
            name='opponent_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jurypoints',
            name='reporter_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
